// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ttSqnOQnkFlSTwdZI_ZiOgA2tD0iUGI',
    appId: '1:524117961573:web:78bd7eaffa0a8b7fd88f8c',
    messagingSenderId: '524117961573',
    projectId: 'les-poulets-de-mamie',
    authDomain: 'les-poulets-de-mamie.firebaseapp.com',
    storageBucket: 'les-poulets-de-mamie.firebasestorage.app',
    measurementId: 'G-WR6R60LPP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1efvakoPswp6IeyCIbAtm3OIG_9dgf4',
    appId: '1:524117961573:android:b3cc03d81a13e296d88f8c',
    messagingSenderId: '524117961573',
    projectId: 'les-poulets-de-mamie',
    storageBucket: 'les-poulets-de-mamie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVNWn88m9QvG9_ekdpm2_sU2Aj2JdMMR0',
    appId: '1:524117961573:ios:51cac8cc5d83bb7cd88f8c',
    messagingSenderId: '524117961573',
    projectId: 'les-poulets-de-mamie',
    storageBucket: 'les-poulets-de-mamie.firebasestorage.app',
    iosBundleId: 'com.isnad.clickCollectKiosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVNWn88m9QvG9_ekdpm2_sU2Aj2JdMMR0',
    appId: '1:524117961573:ios:51cac8cc5d83bb7cd88f8c',
    messagingSenderId: '524117961573',
    projectId: 'les-poulets-de-mamie',
    storageBucket: 'les-poulets-de-mamie.firebasestorage.app',
    iosBundleId: 'com.isnad.clickCollectKiosk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ttSqnOQnkFlSTwdZI_ZiOgA2tD0iUGI',
    appId: '1:524117961573:web:5bc0f75d7cfefd91d88f8c',
    messagingSenderId: '524117961573',
    projectId: 'les-poulets-de-mamie',
    authDomain: 'les-poulets-de-mamie.firebaseapp.com',
    storageBucket: 'les-poulets-de-mamie.firebasestorage.app',
    measurementId: 'G-3GMY14CXPF',
  );
}
